fix: docusaurus config
ethersphere/bee-js-docs pull request #1
Opened 2021-01-30 16:04 UTC by vojtechsimetka

Fixes some local warning, adds correct repo URLs and fixes typerror in lunar search when run locally (see https://github.com/lelouch77/docusaurus-lunr-search/issues/33 )

2021-02-02 22:17 UTC, significance commented
@vojtechsimetka looks good as far as i can see but not building - happy to approve or let me know how best to check otherwise

2021-02-03 09:15 UTC, vojtechsimetka commented
@significance that is because the fix for that was in a different branch. Now I've merged it and it works as you can see here https://github.com/ethersphere/bee-js.github.io/pull/1/checks?check_run_id=1821256237

2021-02-03 16:46 UTC, significance commented on docusaurus.config.js
>    onBrokenLinks: 'warn',
above, url should be `bee-js.ethswarm.org`, note that we need to amend this (and base_url) automatically when we build for Bee in github actions

2021-02-03 16:47 UTC, significance requested changes
just small change as per comment as far as i can see, otherwise looks good!

2021-02-04 11:18 UTC, significance approved these changes
lgtm! 😀

2021-02-04 12:16 UTC, merged